In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [3]:
df=pd.read_csv('heart.csv')
df

age  sex  cp  trestbps  chol  ...  oldpeak  slope   ca  thal  target
0      52    1   0     125.0   212  ...      1.0      2  2.0   3.0       0
1      53    1   0     140.0   203  ...      3.1      0  0.0   3.0       0
2      70    1   0     145.0   174  ...      2.6      0  0.0   3.0       0
3      61    1   0     148.0   203  ...      0.0      2  1.0   3.0       0
4      62    0   0     138.0   294  ...      1.9      1  3.0   2.0       0
...   ...  ...  ..       ...   ...  ...      ...    ...  ...   ...     ...
1020   59    1   1     140.0   221  ...      0.0      2  0.0   2.0       1
1021   60    1   0     125.0   258  ...      2.8      1  1.0   3.0       0
1022   47    1   0     110.0   275  ...      1.0      1  1.0   2.0       0
1023   50    0   0     110.0   254  ...      0.0      2  0.0   2.0       1
1024   54    1   0     120.0   188  ...      1.4      1  1.0   3.0       0

[1025 rows x 14 columns]

In [4]:
df.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope   ca  thal  target
0   52    1   0     125.0   212    0  ...      0      1.0      2  2.0   3.0       0
1   53    1   0     140.0   203    1  ...      1      3.1      0  0.0   3.0       0
2   70    1   0     145.0   174    0  ...      1      2.6      0  0.0   3.0       0
3   61    1   0     148.0   203    0  ...      0      0.0      2  1.0   3.0       0
4   62    0   0     138.0   294    1  ...      0      1.9      1  3.0   2.0       0

[5 rows x 14 columns]

In [5]:
df.tail()

age  sex  cp  trestbps  chol  ...  oldpeak  slope   ca  thal  target
1020   59    1   1     140.0   221  ...      0.0      2  0.0   2.0       1
1021   60    1   0     125.0   258  ...      2.8      1  1.0   3.0       0
1022   47    1   0     110.0   275  ...      1.0      1  1.0   2.0       0
1023   50    0   0     110.0   254  ...      0.0      2  0.0   2.0       1
1024   54    1   0     120.0   188  ...      1.4      1  1.0   3.0       0

[5 rows x 14 columns]

In [6]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [7]:
df.shape

(1025, 14)

In [8]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps    float64
chol          int64
fbs           int64
restecg     float64
thalach     float64
exang         int64
oldpeak     float64
slope         int64
ca          float64
thal        float64
target        int64
dtype: object

In [9]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    1
chol        0
fbs         0
restecg     1
thalach     1
exang       0
oldpeak     0
slope       0
ca          2
thal        1
target      0
dtype: int64

In [10]:
#handle missing values
df['trestbps'].unique()

array([125., 140., 145., 148., 138., 100., 114., 160., 120., 122., 112.,
       132., 118., 128.,  nan, 124., 106., 104., 135., 130., 136., 180.,
       129., 150., 178., 146., 117., 152., 154., 170., 134., 174., 144.,
       108., 123., 110., 142., 126., 192., 115.,  94., 200., 165., 102.,
       105., 155., 172., 164., 156., 101.])

In [11]:
df['trestbps']=df['trestbps'].fillna(df['trestbps'].mean())

In [12]:
df['restecg'].unique()

array([nan,  0.,  1.,  2.])

In [13]:
df['restecg']=df['restecg'].fillna(df['restecg'].mode()[0])

In [14]:
df['thalach'].unique()

array([168., 155., 125.,  nan, 106., 122., 140., 145., 144., 116., 136.,
       192., 156., 142., 109., 162., 165., 148., 172., 173., 146., 179.,
       152., 117., 115., 112., 163., 147., 182., 105., 150., 151., 169.,
       166., 178., 132., 160., 123., 139., 111., 180., 164., 202., 157.,
       159., 170., 138., 175., 158., 126., 143., 141., 167.,  95., 190.,
       118., 103., 181., 108., 177., 134., 120., 171., 149., 154., 153.,
        88., 174., 114., 195., 133.,  96., 124., 131., 185., 194., 128.,
       127., 186., 184., 188., 130.,  71., 161., 137.,  99., 121., 187.,
        97.,  90., 129., 113.])

In [15]:
df['thalach']=df['thalach'].fillna(df['thalach'].mean())

In [16]:
df['ca'].unique()

array([ 2.,  0.,  1.,  3., nan,  4.])

In [17]:
df['ca']=df['ca'].fillna(df['ca'].mode()[0])

In [18]:
df['thal'].unique()

array([ 3.,  2.,  1.,  0., nan])

In [19]:
df['thal']=df['thal'].fillna(df['thal'].mode()[0])

In [20]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [21]:
df

age  sex  cp  trestbps  chol  ...  oldpeak  slope   ca  thal  target
0      52    1   0     125.0   212  ...      1.0      2  2.0   3.0       0
1      53    1   0     140.0   203  ...      3.1      0  0.0   3.0       0
2      70    1   0     145.0   174  ...      2.6      0  0.0   3.0       0
3      61    1   0     148.0   203  ...      0.0      2  1.0   3.0       0
4      62    0   0     138.0   294  ...      1.9      1  3.0   2.0       0
...   ...  ...  ..       ...   ...  ...      ...    ...  ...   ...     ...
1020   59    1   1     140.0   221  ...      0.0      2  0.0   2.0       1
1021   60    1   0     125.0   258  ...      2.8      1  1.0   3.0       0
1022   47    1   0     110.0   275  ...      1.0      1  1.0   2.0       0
1023   50    0   0     110.0   254  ...      0.0      2  0.0   2.0       1
1024   54    1   0     120.0   188  ...      1.4      1  1.0   3.0       0

[1025 rows x 14 columns]

In [22]:
x=df.iloc[:,:-1].values
x

array([[52.,  1.,  0., ...,  2.,  2.,  3.],
       [53.,  1.,  0., ...,  0.,  0.,  3.],
       [70.,  1.,  0., ...,  0.,  0.,  3.],
       ...,
       [47.,  1.,  0., ...,  1.,  1.,  2.],
       [50.,  0.,  0., ...,  2.,  0.,  2.],
       [54.,  1.,  0., ...,  1.,  1.,  3.]], shape=(1025, 13))

In [23]:
y=df.iloc[:,-1].values
y

array([0, 0, 0, ..., 0, 1, 0], shape=(1025,))

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)


In [25]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit(x_train)
x_train=scalar.transform(x_train)
x_test=scalar.transform(x_test)

In [26]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
y_pred

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,

In [27]:
print(knn.predict(scalar.transform([[59,1,1,140.0,221,0,1.0,164,1,0.0,2,0.0,2.0]])))

[1]


In [28]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
score=accuracy_score(y_test,y_pred)
score

0.8603896103896104

In [29]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[130,  31],
       [ 12, 135]])

In [30]:
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.92      0.81      0.86       161
           1       0.81      0.92      0.86       147

    accuracy                           0.86       308
   macro avg       0.86      0.86      0.86       308
weighted avg       0.87      0.86      0.86       308

