In [295]:
import numpy as np
import pandas as pd

df=pd.read_csv('mountains_vs_beaches_preferences.csv')
df

Age      Gender  Income Education_Level  Travel_Frequency  \
0       56        male   71477        bachelor                 9   
1       69        male   88740          master                 1   
2       46      female   46562          master                 0   
3       32  non-binary   99044     high school                 6   
4       60      female  106583     high school                 5   
...    ...         ...     ...             ...               ...   
52439   67      female   85325          master                 3   
52440   37      female  110346        bachelor                 7   
52441   53  non-binary   71080       doctorate                 7   
52442   40      female   75174       doctorate                 9   
52443   33  non-binary   34475          master                 6   

      Preferred_Activities  Vacation_Budget  Location  Proximity_to_Mountains  \
0                   skiing             2477     urban                     175   
1                 swimming             4777  suburban                     228   
2                   skiing             1469     urban                      71   
3                   hiking             1482     rural                      31   
4               sunbathing              516  suburban                      23   
...                    ...              ...       ...                     ...   
52439               hiking             1762  suburban                      51   
52440             swimming             1676     urban                     259   
52441             swimming             3877     urban                     164   
52442             swimming             4620  suburban                     173   
52443               hiking              928  suburban                     218   

       Proximity_to_Beaches Favorite_Season  Pets  Environmental_Concerns  \
0                       267          summer     0                       1   
1                       190            fall     0                       1   
2                       280          winter     0                       0   
3                       255          summer     1                       0   
4                       151          winter     1                       1   
...                     ...             ...   ...                     ...   
52439                   262            fall     1                       0   
52440                    84          spring     1                       0   
52441                    27            fall     0                       1   
52442                    10          summer     0                       1   
52443                   166          spring     1                       0   

       Preference  
0               1  
1               0  
2               1  
3               1  
4               0  
...           ...  
52439           1  
52440           0  
52441           0  
52442           0  
52443           0  

[52444 rows x 14 columns]

In [296]:
df.head()

Age      Gender  Income Education_Level  Travel_Frequency  \
0   56        male   71477        bachelor                 9   
1   69        male   88740          master                 1   
2   46      female   46562          master                 0   
3   32  non-binary   99044     high school                 6   
4   60      female  106583     high school                 5   

  Preferred_Activities  Vacation_Budget  Location  Proximity_to_Mountains  \
0               skiing             2477     urban                     175   
1             swimming             4777  suburban                     228   
2               skiing             1469     urban                      71   
3               hiking             1482     rural                      31   
4           sunbathing              516  suburban                      23   

   Proximity_to_Beaches Favorite_Season  Pets  Environmental_Concerns  \
0                   267          summer     0                       1   
1                   190            fall     0                       1   
2                   280          winter     0                       0   
3                   255          summer     1                       0   
4                   151          winter     1                       1   

   Preference  
0           1  
1           0  
2           1  
3           1  
4           0

In [297]:
df.tail()

Age      Gender  Income Education_Level  Travel_Frequency  \
52439   67      female   85325          master                 3   
52440   37      female  110346        bachelor                 7   
52441   53  non-binary   71080       doctorate                 7   
52442   40      female   75174       doctorate                 9   
52443   33  non-binary   34475          master                 6   

      Preferred_Activities  Vacation_Budget  Location  Proximity_to_Mountains  \
52439               hiking             1762  suburban                      51   
52440             swimming             1676     urban                     259   
52441             swimming             3877     urban                     164   
52442             swimming             4620  suburban                     173   
52443               hiking              928  suburban                     218   

       Proximity_to_Beaches Favorite_Season  Pets  Environmental_Concerns  \
52439                   262            fall     1                       0   
52440                    84          spring     1                       0   
52441                    27            fall     0                       1   
52442                    10          summer     0                       1   
52443                   166          spring     1                       0   

       Preference  
52439           1  
52440           0  
52441           0  
52442           0  
52443           0

In [298]:
df.columns

Index(['Age', 'Gender', 'Income', 'Education_Level', 'Travel_Frequency',
       'Preferred_Activities', 'Vacation_Budget', 'Location',
       'Proximity_to_Mountains', 'Proximity_to_Beaches', 'Favorite_Season',
       'Pets', 'Environmental_Concerns', 'Preference'],
      dtype='object')

In [299]:
df.isna().sum()

Age                       0
Gender                    0
Income                    0
Education_Level           0
Travel_Frequency          0
Preferred_Activities      0
Vacation_Budget           0
Location                  0
Proximity_to_Mountains    0
Proximity_to_Beaches      0
Favorite_Season           0
Pets                      0
Environmental_Concerns    0
Preference                0
dtype: int64

In [300]:
df.dtypes

Age                        int64
Gender                    object
Income                     int64
Education_Level           object
Travel_Frequency           int64
Preferred_Activities      object
Vacation_Budget            int64
Location                  object
Proximity_to_Mountains     int64
Proximity_to_Beaches       int64
Favorite_Season           object
Pets                       int64
Environmental_Concerns     int64
Preference                 int64
dtype: object

In [301]:
df.shape

(52444, 14)

In [302]:
df['Preference'].value_counts()

Preference
0    39296
1    13148
Name: count, dtype: int64

In [303]:
from imblearn.under_sampling import RandomUnderSampler
rus =RandomUnderSampler(random_state=42)

x=df.drop(['Preference'],axis=1)
y=df['Preference']

x_under,y_under=rus.fit_resample(x,y)
df=x_under.copy()
df['Preference']=y_under

In [304]:
df['Preference'].value_counts()



Preference
0    13148
1    13148
Name: count, dtype: int64

In [305]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
df['Gender']=lab.fit_transform(df['Gender'])
df['Education_Level']=lab.fit_transform(df['Education_Level'])
df['Preferred_Activities']=lab.fit_transform(df['Preferred_Activities'])
df['Location']=lab.fit_transform(df['Location'])
df['Favorite_Season']=lab.fit_transform(df['Favorite_Season'])


In [306]:
df.dtypes

Age                       int64
Gender                    int64
Income                    int64
Education_Level           int64
Travel_Frequency          int64
Preferred_Activities      int64
Vacation_Budget           int64
Location                  int64
Proximity_to_Mountains    int64
Proximity_to_Beaches      int64
Favorite_Season           int64
Pets                      int64
Environmental_Concerns    int64
Preference                int64
dtype: object

In [307]:
df.head()

Age  Gender  Income  Education_Level  Travel_Frequency  \
48213   34       1  110050                2                 3   
21001   55       2   76363                2                 2   
17172   31       1   47450                0                 7   
37138   36       2  106496                0                 9   
51293   64       2   29531                1                 4   

       Preferred_Activities  Vacation_Budget  Location  \
48213                     2             2607         2   
21001                     1             3077         2   
17172                     2             3894         0   
37138                     3             1029         2   
51293                     2             3776         2   

       Proximity_to_Mountains  Proximity_to_Beaches  Favorite_Season  Pets  \
48213                     142                   262                2     1   
21001                     273                   202                0     0   
17172                     177                   220                3     1   
37138                     280                    94                2     1   
51293                     193                   195                0     1   

       Environmental_Concerns  Preference  
48213                       1           0  
21001                       0           0  
17172                       0           0  
37138                       0           0  
51293                       0           0

In [309]:
x=df.iloc[:,:-1].values
x

array([[    34,      1, 110050, ...,      2,      1,      1],
       [    55,      2,  76363, ...,      0,      0,      0],
       [    31,      1,  47450, ...,      3,      1,      0],
       ...,
       [    18,      2, 105532, ...,      1,      1,      0],
       [    42,      0,  53330, ...,      2,      1,      1],
       [    67,      0,  85325, ...,      0,      1,      0]],
      shape=(26296, 13))

In [310]:
y=df.iloc[:,-1].values
y

array([0, 0, 0, ..., 1, 1, 1], shape=(26296,))

In [311]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [312]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit(x_train)
x_train=scalar.transform(x_train)
x_test=scalar.transform(x_test)

In [313]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.svm import SVC
knn=KNeighborsClassifier(n_neighbors=7)
nai=BernoulliNB()
sup=SVC()
lst=[knn,nai,sup]

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,ConfusionMatrixDisplay

for i in lst:
    i.fit(x_train,y_train)
    y_pred=i.predict(x_test)
    print("Accuracy score of ",i)
    score=accuracy_score(y_test,y_pred)
    print(score)
    print("confusion_matrix of ",i)
    cm=confusion_matrix(y_test,y_pred)
    print(cm)
    print("report of ",i)
    report=classification_report(y_test,y_pred)
    print(report)
    print('-'*100)

Accuracy score of  KNeighborsClassifier(n_neighbors=7)
0.9044238813537837
confusion_matrix of  KNeighborsClassifier(n_neighbors=7)
[[3308  635]
 [ 119 3827]]
report of  KNeighborsClassifier(n_neighbors=7)
              precision    recall  f1-score   support

           0       0.97      0.84      0.90      3943
           1       0.86      0.97      0.91      3946

    accuracy                           0.90      7889
   macro avg       0.91      0.90      0.90      7889
weighted avg       0.91      0.90      0.90      7889

----------------------------------------------------------------------------------------------------
Accuracy score of  BernoulliNB()
0.926860185067816
confusion_matrix of  BernoulliNB()
[[3422  521]
 [  56 3890]]
report of  BernoulliNB()
              precision    recall  f1-score   support

           0       0.98      0.87      0.92      3943
           1       0.88      0.99      0.93      3946

    accuracy                           0.93      7889
   macro av

In [314]:
df.head()

Age  Gender  Income  Education_Level  Travel_Frequency  \
48213   34       1  110050                2                 3   
21001   55       2   76363                2                 2   
17172   31       1   47450                0                 7   
37138   36       2  106496                0                 9   
51293   64       2   29531                1                 4   

       Preferred_Activities  Vacation_Budget  Location  \
48213                     2             2607         2   
21001                     1             3077         2   
17172                     2             3894         0   
37138                     3             1029         2   
51293                     2             3776         2   

       Proximity_to_Mountains  Proximity_to_Beaches  Favorite_Season  Pets  \
48213                     142                   262                2     1   
21001                     273                   202                0     0   
17172                     177                   220                3     1   
37138                     280                    94                2     1   
51293                     193                   195                0     1   

       Environmental_Concerns  Preference  
48213                       1           0  
21001                       0           0  
17172                       0           0  
37138                       0           0  
51293                       0           0

In [315]:
print(sup.predict(scalar.transform([[69,1,88740,3,1,3,4777,1,228,190,0,0,1]])))

[0]
